/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui.Dialog_ {
    export class FloatMsgUI extends Scene {
		public ani1:Laya.FrameAnimation;
		public sp_floatMsg:Laya.Sprite;
		public lab_floatMsg:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Dialog_/FloatMsg");
        }
    }
}
export module ui.Welcome {
    export class LoginUI extends Scene {
		public ani1:Laya.FrameAnimation;
		public sp_loginBox:Laya.Sprite;
		public input_userName:Laya.TextInput;
		public input_userKey:Laya.TextInput;
		public lab_title:Laya.Label;
		public btn_login:Laya.Button;
		public btn_register:Laya.Button;
		public sp_progress:Laya.Sprite;
		public sp_progressW:Laya.Sprite;
		public sp_progressL:Laya.Sprite;
		public sp_progressT:Laya.Label;
		public sp_gameName:laya.display.Text;
		public sp_registerBox:Laya.Sprite;
		public input_registerUserName:Laya.TextInput;
		public input_registerUserKey:Laya.TextInput;
		public btn_toLogin:Laya.Button;
		public btn_toRegister:Laya.Button;
		public input_registerNickName:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Welcome/Login");
        }
    }
}