/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import WelComeController from "./Controller/WelCome/WelComeController"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1440;
    static height:number=750;
    static scaleMode:string="fixedheight";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Welcome/Login.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Controller/WelCome/WelComeController.ts",WelComeController);
    }
}
GameConfig.init();